name: CI_mypy

on: [pull_request, push]

jobs:
  run_mypy:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v7
    - name: Install mypy
      run: |
        sudo apt-get install -y python3
        python3 -m venv .venv
        .venv/bin/pip install mypy==2.3.1
    - name: Create default local config
      run: cp chb/util/ConfigLocal.template chb/util/ConfigLocal.py
    - name: Run mypy
      run: |
        PYTHONPATH=$PWD .venv/bin/mypy chb
